apps/authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from apps.authentication.views import RegistrationView, ConfirmSignUpView, TwoFactorAuthenticationView
from apps.authentication.views import (RegistrationView, ConfirmSignUpView, UserProfileFormView,
                                       UserProfileView, UserProfileUpdate, AboutView, WelcomeView)
app_name = 'auth'
urlpatterns = [
    path('signup/', RegistrationView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/', UserProfileFormView.as_view(), name='userprofile'),
    path('view_profile/', UserProfileView.as_view(), name='userprofileview'),
    path('update_profile/', UserProfileUpdate.as_view(), name='userprofileupdate'),
    path('email-confirmation/<uidb64>/<token>/', ConfirmSignUpView.as_view(
    ), name="email_confirmation"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='authentication/password_reset_confirm.html',
                                                                 email_template_name='authentication/password_reset_email.html', success_url='done'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='authentication/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html', success_url='done'), name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='authentication/password_change_done.html'), name='password_change_done'),
    path('otp/', TwoFactorAuthenticationView.as_view(), name='otp'),

]

apps/coins/urls.py
from django.urls import path
from django.views.generic import TemplateView, FormView, View, ListView
from . views import IndexView, ExchangeRateView

app_name = 'coins'
urlpatterns = [
    path('', IndexView.as_view(), name = 'home'),
    path('exchange/', TemplateView.as_view(template_name='exchange.html'), name='exchange'),

]

psalm/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from apps.authentication.views import WelcomeView, AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('apps.authentication.urls', namespace='auth')),
    path('', include('apps.coins.urls', namespace='apps.coins')),
    path('welcome/', WelcomeView.as_view(), name='welcome'),
    path('aboutus/', AboutView.as_view(), name='aboutus'),
] + static(settings.MEDIA_URL,  document_root=settings.STATIC_ROOT)

apps/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.utils.crypto import get_random_string


class User(AbstractUser):
    first_name = models.CharField(max_length=200, blank=True, default="")
    last_name = models.CharField(max_length=200, blank=True, default="")
    phone_number = models.CharField(max_length=20, blank=True, default="")
    two_factor_status = models.BooleanField()


class UserProfile(models.Model):
    """User Profile"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=128, help_text='Country of Permanent Residence')
    state = models.CharField(max_length=128, help_text='State of Permanent Residence')
    city = models.CharField(max_length=128, help_text='City of Permanent Residence')
    landmark = models.CharField(
        max_length=128, help_text='Enter a landmark closest to you')
    address_line_1 = models.CharField(
        max_length=128, help_text='House name/Flat No')
    address_line_2 = models.CharField(
        max_length=128, help_text='Street Name/No')
    address_line_3 = models.CharField(
        max_length=128, help_text='Locality Name')
    pincode = models.CharField(max_length=128, null=False, help_text='pincode/zipcode of your area')

    def __str__(self):
        return self.user.email

apps/authentication/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _

from .users import UserModel
from .users import UsernameField
from .models import UserProfile
User = UserModel()


class RegistrationForm(UserCreationForm):
    """
    Form for registering a new user account.

    """
    required_css_class = 'required'
    email = forms.EmailField(label=_("E-mail"))

    class Meta:
        model = User
        fields = (UsernameField(), "email", "first_name", "last_name", "two_factor_status")
    
    def clean_username(self):
        username = self.cleaned_data.get('username', '').lower()
        if User.objects.filter(**{UsernameField(): username}).exists():
            raise forms.ValidationError(_('A user with that username already exists.'))

        return username

    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.

        """
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError(_("This email address is already in use. Please supply a different email address."))
        return self.cleaned_data['email']



class ResendActivationForm(forms.Form):
    required_css_class = 'required'
    email = forms.EmailField(label=_("E-mail"))


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('address_line_1','address_line_2','address_line_3','landmark','city','state', 'country', 'pincode')

apps/authentication/views.py
import random

from twilio.rest import Client

from django.utils import six
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.template import RequestContext
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.utils.module_loading import import_string
from django.utils.encoding import force_bytes, force_text
from django.shortcuts import redirect, render_to_response, render
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.views.decorators.debug import sensitive_post_parameters
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import TemplateView, View, FormView, UpdateView, DetailView


from apps.authentication.models import User, UserProfile
from apps.authentication.forms import ResendActivationForm, RegistrationForm, UserProfileForm

class RegistrationView(FormView):
    """
    User registration view.

    """
    form_class = RegistrationForm
    success_url = None
    template_name = 'authentication/signup.html'

    def form_valid(self, form):
        import pdb; pdb.set_trace()
        new_user = form.save()
        if new_user:
            new_user.is_active = False
            new_user.save()
            token = account_activation_token.make_token(new_user)
            confirm_url = self.request.scheme+"://"+self.request.META['HTTP_HOST']+".io"+\
            reverse('auth:email_confirmation', kwargs={'uidb64': urlsafe_base64_encode(force_bytes(new_user.pk)).decode("utf-8"),'token': token})
            html_message = "Click the link to verify email address <a href='"+confirm_url+"'>Verify</a>"
            try:
                send_mail('Confrim Registration',
                          '',
                          settings.DEFAULT_FROM_EMAIL,
                          [new_user.email],
                          html_message=html_message,
                          fail_silently=False
                          )
            except:
                pass
            return render_to_response('authentication/success.html')
        else:
            return redirect(reverse('signup'))


class TwoFactorAuthenticationView(TemplateView):
    """
    Enabling 2FA.
    This will set a otp-verified in session when user enters the correct otp.
    """
    template_name = "authentication/otp.html"

    def dispatch(self,request,*args,**kwargs):
        if not self.request.user.phone_number and not self.request.method == "POST":
            return render(self.request,"authentication/mobile.html")
        elif self.request.user.phone_number and not self.request.method == "POST":
            pin =  self._get_pin()
            self.request.session['otp'] = pin
            self.send_otp(pin,self.request.user.phone_number)
            return render(self.request,"authentication/otp.html")
        else:
            return self.post(self,request,args,kwargs)

    def post(self,request,*args,**kwargs):
        number = self.request.POST.get('phone_number')
        if number:
            User.objects.filter(id = self.request.user.id).update(phone_number=number)
            pin =  self._get_pin()
            self.request.session['otp'] = pin
            try:
                self.send_otp(pin,number)
            except:
                User.objects.filter(id = self.request.user.id).update(phone_number='')
                return render(self.request,"authentication/mobile.html",{"error":"Please Check the Phone Number"})
            return render(self.request,"authentication/otp.html")
        else:
            if self.request.POST.get('otp') == self.request.session['otp']:
                del self.request.session['otp']
                self.request.session['otp-verified'] = True
                device = self.request.META['HTTP_USER_AGENT']
                ip = self.request.META['REMOTE_ADDR']
                AccessLog.objects.create(user= self.request.user, device=device, ip=ip)
                return redirect(reverse('welcome'))
            else:
                pin = self._get_pin()
                self.request.session['otp'] = pin
                self.send_otp(pin,self.request.user.phone_number)
                return render(self.request,"authentication/otp.html")

    def send_otp(self,pin,number):
        client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
        message = client.messages.create(
                                body="Your verification code is %s" % pin,
                                to=number,
                                from_=settings.TWILIO_FROM_NUMBER,
                            )

    def _get_pin(self,length=5):
        """ Return a numeric PIN with length digits """
        return str(random.sample(range(10**(length-1), 10**length), 1)[0])


class AccountActivationTokenGenerator(PasswordResetTokenGenerator):
    """ Overriding default Password reset token generator for email confirmation"""

    def _make_hash_value(self, user, timestamp):
        return (six.text_type(user.pk) + six.text_type(timestamp)) + six.text_type(user.is_active)


account_activation_token = AccountActivationTokenGenerator()


class ConfirmSignUpView(View):
    """ Confirming sign up via link provided in email"""
    template_name = 'authentication/email_verified.html'

    def get(self, request, *args, **kwargs):
        """ Ckecking token and conforming account activation"""
        pk = force_text(urlsafe_base64_decode(kwargs.get('uidb64')))
        token = kwargs.get('token')
        user = get_object_or_404(User, pk=pk)
        if account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            return render(request, self.template_name, {'error': False})
        else:
            return render(request, self.template_name, {'error': True})


class UserProfileFormView(FormView):
    form_class = UserProfileForm
    template_name = 'authentication/userprofile.html'
    success_url = reverse_lazy('coins:home')

    def form_valid(self, form):
        temp_form = form.save(commit=False)
        temp_form.user = self.request.user
        temp_form.save()
        messages.add_message(self.request, messages.SUCCESS,
                             'Success!. Profile Updated')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR,
                             'Error. Please recheck form')

        return self.render_to_response(self.get_context_data(form=form))


class UserProfileView(DetailView):
    model = UserProfile
    context_object_name = 'userprofile'
    template_name = 'authentication/user_profile_view.html'

    def dispatch(self, request, *args, **kwargs):
        try:
            self.object = self.request.user.userprofile
        except:
            return redirect('auth:userprofile')

        self.get_object()
        return super(UserProfileView, self).get(request, *args, **kwargs)

    def get_object(self):
        return self.request.user.userprofile


class UserProfileUpdate(UpdateView):
    model = UserProfile
    fields = ('address_line_1', 'address_line_2', 'address_line_3',
              'landmark', 'city', 'state', 'country', 'pincode')

    template_name = 'authentication/userprofile.html'
    success_url = reverse_lazy('auth:userprofileview')

class UserProfileView(DetailView):
    model = UserProfile
    context_object_name = 'userprofile'
    template_name = 'authentication/user_profile_view.html'

    def dispatch(self, request, *args, **kwargs):
        try:
            self.object = self.request.user.userprofile
        except:
            return redirect('auth:userprofile')

        self.get_object()
        return super(UserProfileView, self).get(request, *args, **kwargs)

    def get_object(self):
        return self.request.user.userprofile


class UserProfileUpdate(UpdateView):
    model = UserProfile
    fields = ('address_line_1', 'address_line_2', 'address_line_3',
              'landmark', 'city', 'state', 'country', 'pincode')

    template_name = 'authentication/userprofile.html'
    success_url = reverse_lazy('auth:userprofileview')

    def get_object(self):
        return self.request.user.userprofile

class WelcomeView(View):
    template_name = 'welcome.html'

    def get(self,request,*args,**kwargs):
        if self.request.user.two_factor_status:
            return redirect(reverse('auth:otp'))
        else:
            return render(request,self.template_name)

class AboutView(TemplateView):
    template_name = 'aboutus.html'

templates/authentication/email_verified.html
<!DOCTYPE html> {% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
	<title>Hashcoin</title>
	<meta charset="utf-8">
	<!--[if IE]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<![endif]-->
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/animations.css' %}">
	<link rel="stylesheet" href="{% static 'css/crypto_custom.css' %}">
	<script src="{% static 'js/vendor/modernizr-2.6.2.min.js' %}"></script>
	<!--[if lt IE 9]>
		<script src="{% static 'js/vendor/html5shiv.min.js' %}"></script>
		<script src="{% static 'js/vendor/respond.min.js' %}"></script>
		<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
	<![endif]-->
</head>

<body>
	<!--[if lt IE 9]>
		<div class="bg-danger text-center">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/" class="highlight">upgrade your browser</a> to improve your experience.</div>
	<![endif]-->
	<div class="preloader">
		<div class="preloader_image"></div>
	</div>
	<section class="success-bg full-page">

		<div class="container">
			<div class="row">
				<div class="col-sm-10 text-center success-center white-font">
								<a href="./" class="logo top_logo top_offset_logo">
									<img src="{% static 'img/logo.png' %}" alt="" class="img-fluid">
								</a>

					{% if error %}
						<h2>Error</h2>
					{% else %}
						<h2 class="white-font">Success</h2>
                    {% endif %}
					<div class="">
                        {% if error %}
                            <h4>You followed an invalid link. Please check.</h4>
						{% else %}
							<h3 class="white-font">Successfully Verified. Now You can login with your credentials.</h3>
						{% endif %}
					</div>
					{% if not error %}
					<span>
						<br>click
						<a href="{% url 'auth:login' %}" class="success-href">Here</a> to login</span>
					{% endif %}
				</div>
			</div>
		</div>
	</section>


	<script src="{% static 'js/compressed.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	<script src="{% static 'js/aos.js' %}"></script>
	<script>
		AOS.init();
	</script>
	<!-- Google Map Script -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTwYSMRGuTsmfl2z_zZDStYqMlKtrybxo"></script>

	<script src="{% static 'js/aos.js' %}"></script>
</body>

</html>

templates/authentication/logged_out.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block content %}

<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="{% url 'admin:index' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

templates/authentication/login.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="page-header-dark col-12">
	<h1 class="page-header-font-yellow">Login</h1>
	<div class="breadcrumbs-dark">
		<span>Home</span>
		<span>/</span>
		<a href="">
			<span>Login</span>
		</a>
	</div>
</div>

<section class="col-12">
	<div class="container">
		<div class="row mt-5">

			<div class="col-sm-6 offset-sm-3 text-center mt-5 mb-5">
				<div id="form-error" style="color: red;">{{ form.non_field_errors }}</div>
				<form name="login-form" class="contact-form columns_padding_10" method="post" action="./">
					{% csrf_token %}

					<div class="col-12">
					{% for field in form %}
						{% if field.errors%}
						<div class="form-field-errors text-left col-sm-6 offset-sm-3 no-list" style="color: red;">
							{{ field.errors }}
							<span class="help no-list" >{{ field.help_text|safe }}</span>
						</div>
						{% endif %}
						<div class="col-sm-12 text-justify">
							<div class="form-group bottommargin_0">
								{% if field.field.widget.input_type == 'password' %}
								<input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{field.id_for_label}}" class="form-control signup-input"
									placeholder="{{field.label}}" value=""> 

								{% else %}
								<input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{field.id_for_label}}" class="form-control signup-input"
									placeholder="{{field.label}}" value="{{ field.value|default_if_none:''}}"> {% endif%}
	
							</div>
						<!-- {% if field.help_text %}
						<p class="help ">{{ field.help_text|safe }}</p>
						{% endif %} -->
					</div>
					{% endfor %}
					<div class="col-12 text-center">

						<div class="g-recaptcha" data-sitekey="6LdEcUIUAAAAAOdzadXa7dD9wVAs-g-AtegbLlM0"></div>
					</div>

				</div>
	
					<div align="center" class="">
						<div class="contact-form-submit topmargin_20">
							<button type="button" onclick="validateForm()"  class="btn btn-secondary exchange-next ">Login</button>
						</div>
					</div>
				</form>
				<a href="{% url 'auth:password_reset'%}">Forgot password?</a>
			</div>
		</div>
		<!--.row -->
	</div>
	<!--.container -->
</section>
<script type="text/javascript">
function validateForm() {	
    var recaptcha = document.forms["login-form"]["g-recaptcha-response"].value;
    if (recaptcha == "") {
        $("#form-error").text("Recaptcha Failed");
    }
    else{
    	$("form").submit();
    }
}
</script>
{% endblock %}

templates/authentication/mobile.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section class="col-12">
	<div class="container">
		<div class="row mt-5">

			<div class="col-sm-6 offset-sm-3 text-center mt-5 mb-5">
				<div style="color: red;">{{ error }}</div>
				<form class="contact-form columns_padding_10" method="post" action="./">
					{% csrf_token %}
					<div class="">
						<div class="form-group ">
							<input type="tel" size="30" value="" name="phone_number" id="id_phone_number"  class="form-control login-input" placeholder="Mobile Number">
						</div>
					</div>
					<div align="center" class="">
						<div class="contact-form-submit topmargin_20">
							<button type="button" onclick="sendData();" class="btn btn-secondary exchange-next">Send OTP</button>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!--.row -->
	</div>
	<!--.container -->
</section>

{% endblock %}
{% block script %}
<script type="text/javascript">
    $("#id_phone_number").intlTelInput();
    function sendData(){
    	value = $("#id_phone_number").val()
    	$("#id_phone_number").intlTelInput("setNumber", "+"+$("#id_phone_number").intlTelInput("getSelectedCountryData").dialCode+value);
    	$("form").submit();
    }

</script>
{% endblock %}

templates/authentication/otp.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section class="col-12">
	<div class="container">
		<div class="row mt-5">

			<div class="col-sm-6 offset-sm-3 text-center mt-5 mb-5">
				<div style="color: red;">{{ form.non_field_errors }}</div>
				<form class="contact-form columns_padding_10" method="post" action="./">
					{% csrf_token %}
					<div class="">
						<div class="form-group ">
							<input type="text" size="30" value="" name="otp" id="id_otp" class="form-control login-input" placeholder="OTP">
						</div>
					</div>
					<div align="center" class="">
						<div class="contact-form-submit topmargin_20">
							<button type="submit" class="btn btn-secondary exchange-next ">Verify</button>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!--.row -->
	</div>
	<!--.container -->
</section>

{% endblock %}

templates/authentication/password_change_done.html
{% extends "base.html" %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}

{% block content %}
<div class="col-12 text-center p-5">


    <h3>{% trans 'Your password is changed successfully.' %}</h3>
    <p>Please login with your new password</p>
    <div class="pb-5 text-center col-12 white-font mtb-auto">

        <a class="btn btn-secondary exchange-next" href="{% url 'auth:login' %}">Login</a>
    </div>
</div>
{% endblock %}

templates/authentication/password_reset_confirm.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="page-header-dark col-12">
	<h1 class="page-header-font-yellow">Password Reset</h1>
	<div class="breadcrumbs-dark">
		<span>Home</span>
		<span>/</span>
		<a href="">
			<span>Password Reset</span>
		</a>
	</div>
</div>
<section class="col-12">
	<div class="container">
		<div class="row mt-5">

			<div class="col-sm-6 offset-sm-3 text-center mt-5 mb-5">
				<div style="color: red;">{{ form.non_field_errors }}</div>
				<form class="contact-form " method="post" action="./">
					{% csrf_token %}
					<div class="">
						<div class="form-group ">
							<input type="text" size="30" value="" name="email" id="id_email" class="form-control login-input" placeholder="email">
							<span>
								<p>{{form.email.errors}}</p>
							</span>
						</div>
					</div>
					<div align="center" class="">
						<div class="contact-form-submit topmargin_20">
							<button type="submit" name="contact_submit" class="btn btn-secondary exchange-next ">Reset Password</button>
						</div>
					</div>
				</form>
				<div class="col-6 offset-3 d-flex  justify-content-around mt-3">
					<a href="{% url 'auth:login'%}">Login</a>
					<span>&nbsp;|&nbsp;</span>
					<a href="{% url 'auth:signup' %}">Signup</a>
				</div>
			</div>
		</div>
		<!--.row -->
	</div>
	<!--.container -->


	{% endblock %}

templates/authentication/password_reset_done.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="col-sm-12 text-center p-5">
	<h2>Password reset sent</h2>
</div>

<section class=" text-center">

			<div class="col-sm-6 offset-sm-3 text-justify">

				<p>
					We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive
					them shortly. If you don't receive an email, please make sure you've entered the address you registered with, and check
					your spam folder.
					<p>
			</div>
<div class="pb-5 text-center col-12 white-font mtb-auto">

	<a class="btn btn-secondary exchange-next" href="{% url 'auth:login' %}">Login</a>
</div>
</section>

{% endblock %}

templates/authentication/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'auth:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

templates/authentication/success.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="page-header-dark col-12">
	<h1 class="page-header-font-yellow">SUCCESS</h1>

</div>
<section class="col-12 mt-5 p-5">
	<div class="container ">
		<div class="row text-center">

			<h3 class="margin-center" style="color:#000">Please verify your email id to begin.</h3>

		</div>
		<!--.row -->
	</div>
	<!--.container -->
</section>
{% endblock %}

templates/authentication/userprofile.html
{% extends 'base.html' %} {% load static %} {% block carousel%}
<div class="container event-login-body">

    <div class="col-12 col-md-8 offset-md-2">
        <form id="side-2" class="flip" action="" method="POST">
            <div class="col-12  event-login-header text-center">
               <h1> Signup</h1>
            </div>
            <div class="event-login pad20 p-sm-5 font-darkgrey">
                {% for field in form %}
                <div class="fieldWrapper mt-3">
                    {% if field.errors%}
                    <div class="form-field-errors">
                        {{ field.errors }}
                    </div>
                    {% endif %} {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                    <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{field.id_for_label}}" 
                    class="col-12 input-login profile-input"placeholder="{{field.label}}" value="{{ field.value|default_if_none:''}}">


                </div>

                {% endfor %} {% csrf_token %}
                <!-- <input id="id_email" type="text" class="col-12 input-login" placeholder="email">

                        <input  id="id_phone" type="text" class="col-12 input-login" placeholder="phone">
                        <input id="id_password"  type="password" class="col-12 input-login" placeholder="password">
                        <input id="id_retype_password" type="password" class="col-12 input-login" placeholder="Renter-password"> -->
                <input type="submit" class="col-12 btn btn-dark my-3" value="update">

                <div class="col-12 my-3">
                    <a href="{% url 'auth:password_reset' %}" class="col-xs-12 col-sm-6">Forgot Password</a>
                    <a href="{% url 'auth:login' %}" id="login" class="col-xs-12 col-sm-6">Login</a>
                </div>
            </div>
        </form>
    </div>

</div>
{% endblock %}