apps/authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from apps.authentication.views import RegistrationView, ConfirmSignUpView, TwoFactorAuthenticationView
from apps.authentication.views import (RegistrationView, ConfirmSignUpView, UserProfileFormView,
                                       UserProfileView, UserProfileUpdate, AboutView, WelcomeView)
app_name = 'auth'
urlpatterns = [
    path('signup/', RegistrationView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/', UserProfileFormView.as_view(), name='userprofile'),
    path('view_profile/', UserProfileView.as_view(), name='userprofileview'),
    path('update_profile/', UserProfileUpdate.as_view(), name='userprofileupdate'),
    path('email-confirmation/<uidb64>/<token>/', ConfirmSignUpView.as_view(
    ), name="email_confirmation"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='authentication/password_reset_confirm.html',
                                                                 email_template_name='authentication/password_reset_email.html', success_url='done'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='authentication/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html', success_url='done'), name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='authentication/password_change_done.html'), name='password_change_done'),
    path('otp/', TwoFactorAuthenticationView.as_view(), name='otp'),

]

apps/coins/urls.py
from django.urls import path
from django.views.generic import TemplateView, FormView, View, ListView
from . views import IndexView, ExchangeRateView

app_name = 'coins'
urlpatterns = [
    path('', IndexView.as_view(), name = 'home'),
    path('exchange/', TemplateView.as_view(template_name='exchange.html'), name='exchange'),

]

psalm/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from apps.authentication.views import WelcomeView, AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('apps.authentication.urls', namespace='auth')),
    path('', include('apps.coins.urls', namespace='apps.coins')),
    path('welcome/', WelcomeView.as_view(), name='welcome'),
    path('aboutus/', AboutView.as_view(), name='aboutus'),
] + static(settings.MEDIA_URL,  document_root=settings.STATIC_ROOT)

templates/aboutus.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="page-header-dark col-12">
    <h1 class="page-header-font-yellow">Wallets</h1>
    <div class="breadcrumbs-dark">
        <span>Home</span>
        <span>/</span>
        <a href="">
            <span>About US</span>
        </a>
    </div>
</div>
<div class="col-10 offset-1 mt-5">
    <div class="row text-justify">
        <h1>
            About Us</h1>
        <p>


            Psalm is not just a revolutionary exchange where investors from across the globe can trade cryptocurrency with ease. We are
            a complete non-banking financial digital institution giving community members complete control of their “money”
            and investment decisions. We are dedicated to bringing our real-life finance skills and expertise to our global
            user friendly community platform. As supply and demand are created with opportunities to digitize common everyday
            assets, more cryptocurrency will be designed to monetize profits for our community.

        </p>

        <h1>Corporate Vision</h1>
        <p>The vision of our platform is different; we are focused on building a community non-bank for the blockchain era,
            which will eventually become a one-stop shop for all financial services. Brick and mortar banks have become just
            institutions with very little depositor transparency, “fine print” with increasing regulations, high fees to
            access your capital, increased penalties, and monthly account service fees. As a digitize virtual community non-bank
            financial institution, we will be able to take back control of our money. We are dedicated to bringing our real-life
            finance skills and expertise to our global user friendly community platform. As supply and demand are created
            with opportunities to digitize common everyday assets, more cryptocurrency will be designed to monetize profits
            for our community members. We will become a top cryptocurrency fintech non-banking company in the world in the
            next 3 years

        </p>
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html> {% load static %}

<html>

<head>
    <title>Psalm</title>
    <meta charset="utf-8">
    <!--[if IE]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<![endif]-->
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/crypto_custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/intlTelInput.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> {% block style %} {% endblock style %}

    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <!--[if lt IE 9]>
		<script src="{% static 'js/vendor/html5shiv.min.js' %}"></script>
		<script src="{% static 'js/vendor/respond.min.js' %}"></script>
		<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
	<![endif]-->
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>

<body>
    <div class="preloader">
        <div class="preloader_image"></div>
    </div>
    <div class="white-font bg-blue p-3 d-md-flex justify-content-around">
        <div class="col-md-3  ">
           <a href="{% url 'coins:home' %}"> <span class="logo-font d-flex align-items-center"><img src="{% static 'images/theme/Logo.png' %}" class=" logo img-fluid"> &nbsp; Psalm</span></a>
        </div>
        <div class="col-md-3 d-flex flex-row justify-content-around">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ request.user.first_name}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right " aria-labelledby="userMenu">
                        <a class="dropdown-item" href="">Wallet</a>
                        <a class="dropdown-item" href="">Transactions</a>
                        <a class="dropdown-item" href="{% url 'auth:password_change' %}">Change password</a>
                        <a class="dropdown-item" href="{% url 'auth:userprofileview' %}">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/auth/logout/">Log out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <a class="nav-item nav-link" href="/auth/login/">
                <span class="white-font bit-font">
                    <i class="fa fa-user "> </i> LOGIN</span>
            </a>
            <a class="nav-item nav-link " href="/auth/signup/">
                <span class="white-font bit-font">
                    <i class="fa fa-sign-in "> </i> SIGNUP</span>
            </a>


            {% endif %}
        </div>
    </div>
    <nav class="navbar navbar-expand-lg nav-darkblue crypto-nav sticky-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars" aria-hidden="true"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
            <div class="navbar-nav text-uppercase mr-auto">
                <a class="nav-item nav-link active" href="{% url 'coins:home' %}">home</a>
                <a class="nav-item nav-link" href="{% url 'coins:exchange' %}">Exchange</a>
                {% if user.is_authenticated %}
                <a class="nav-item nav-link " href="">Wallet</a>
                <a class="nav-item nav-link " href="">Transactions</a>
                {% endif %}



            </div>

        </div>
    </nav>
    <div class="font-darkgrey">
        <!-- section caraousel-->

        {% block carousel%} {% endblock carousel %} {% block content_wallet %} {% endblock content_wallet %}
        <!-- end caraousel -->
        <div class="container-fluid">
            <div class="row">
                {% block content %} {% endblock content%}
            </div>
        </div>
        <!-- section about bitcoin -->
    </div>
    <section class=" footer">
        <div class=" bg-black p-5">
            <div class="col-12 p-3">
                <span>Access your Bitcoin Wallet securely</span>
            </div>
            <div class="col-12 p-3">
                <span class="footer-bold sansthick">biT-Exchange on all your devices</span>
            </div>
            <div class="col-12 p-3">
                <img class="img-fluid mt-1" src="{% static 'images/theme/appstore.png' %}">
                <img class="img-fluid mt-1" src="{% static 'images/theme/playstore.png'%}">
            </div>
        </div>
        <div class=" p-5 bg-navyblue">
            <div class="row col-md-10 offset-md-1 text-left">

                <div class="col-sm-6 col-md-3 p-3">
                    <a href="{% url 'aboutus' %}">About Us</span></a>
                    <div class="footer-header-line"></div>
                    <ul class="mt-3">
                        <li>
                            <a href="#">Legal & Security</a>
                        </li>
                        <li>
                            <a href="#">Help Centre</a>
                        </li>
                        <li>
                            <a href="#">Terms of Use</a>
                        </li>
                        <li>
                            <a href="#">Refund Policy</a>
                        </li>
                        <li>
                            <a href="#">Press</a>
                        </li>
                    </ul>
                </div>

                <div class="col-sm-6 col-md-3 p-3">
                    <span class="footer-header">Services</span>
                    <div class="footer-header-line"></div>
                    <ul class="mt-3">
                        <li>
                            <a href="#">Buy Bitcoin</a>
                        </li>
                        <li>
                            <a href="#">Buy Ethereum</a>
                        </li>
                        <li>
                            <a href="#">Sell Bitcoins</a>
                        </li>
                        <li>
                            <a href="#">Bitcoin Trading</a>
                        </li>
                        <li>
                            <a href="#">Margin Trading</a>
                        </li>
                    </ul>
                </div>

                <div class="col-sm-6 col-md-3 p-3">
                    <span class="footer-header">Information</span>
                    <div class="footer-header-line"></div>
                    <ul class="mt-3">
                        <li>
                            <a href="#">Payment Options</a>
                        </li>
                        <li>
                            <a href="#">Fee Schedule</a>
                        </li>
                        <li>
                            <a href="#">Getting Started</a>
                        </li>
                        <li>
                            <a href="#">Identity Verification Guide</a>
                        </li>
                        <li>
                            <a href="#">Card Verification Guide</a>
                        </li>
                    </ul>
                </div>

                <div class="col-sm-6 col-md-3 p-3">
                    <span class="footer-header">Contact Us</span>
                    <div class="footer-header-line"></div>
                    <ul class="mt-3">
                        <li>
                            <a href="#">info@Coinzel.net
                            </a>
                        </li>
                        <li>
                            <a href="#">press@coinzel.net </a>
                        </li>
                        <li>
                            <a href="#">support@coinzel.net</a>
                        </li>
                        <li>
                            <a href="#">complaints@coinzel.net </a>
                        </li>
                        <li>
                            <a href="#">+44 20 8133 5474</a>
                        </li>
                    </ul>
                </div>



            </div>
        </div>



    </section>

    <div class="p-3 p-sm-0 d-flex  justify-content-around align-items-center bg-lightblue container-fluid">
        <div class="row col-12 d-flex  justify-content-around align-items-center">

            <div class="col-12 col-md-4 mt-2">
                <div class="col-12 col-sm-8 offset-sm-2  d-flex justify-content-around align-items-center p-2">
                    <div class="fsc">
                        <i class="fa fa-facebook p-2" aria-hidden="true"></i>
                    </div>
                    <div class="fsc">
                        <i class="fa fa-twitter  p-2" aria-hidden="true"></i>
                    </div>
                    <div class="fsc">
                        <i class="fa fa-linkedin p-2 " aria-hidden="true"></i>
                    </div>
                    <div class="fsc">
                        <i class="fa fa-github  p-2" aria-hidden="true"></i>
                    </div>
                </div>

            </div>
            <div class="col-12 col-md-4 mt-2 text-center">
                <span class=" white-font sansthick">Copyright by biT-Exchange Ltd 2017.
                </span>
            </div>
            <div class="col-12 col-md-4 mt-2 text-center">
                <span class="margin-center">
                    <img class="img-fluid" src="{% static 'images/theme/bankicons.png' %}">
                </span>
            </div>
        </div>

    </div>


    <!-- script -->
    <script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.js' %}"></script>
    <script src="{% static 'js/custom_crypto.js' %}"></script>
    <script src="{% static 'js/intlTelInput.js' %}"></script>
    {% block script %} {% endblock script %}

</body>

</html>

templates/exchange.html
{% extends 'base.html' %} {% load static %}

{% block style %}

<link rel="stylesheet" href="{% static 'css/piechart.css' %}">
{% endblock %}

{% block content %}



<section class="container-fluid">
	<div class="row">
		<div class="col-10 offset-1 dark-font d-flex flex-wrap align-content-around">
			<div class="col-4 col-sm-3 col-md-2 p-2 p-sm-5">
				<span>
					<i class="fa fa-usd" aria-hidden="true"></i> 0.00</span>
			</div>
			<div class="col-4 col-sm-3 col-md-2  p-2 p-sm-5">
				<span>
					<i class="fa fa-eur" aria-hidden="true"></i> 0.00</span>
			</div>
			<div class="col-4 col-sm-3 col-md-2  p-2 p-sm-5">
				<span>
					<i class="fa fa-btc" aria-hidden="true"></i> 0.00</span>
			</div>
			<div class="col-12 col-sm-3 col-md-2  p-2 p-sm-5 ml-auto">
				<a class="exhange-btn-back">Back</a>
			</div>
		</div>
	</div>
</section>


<section class="section-blue container-fluid white-font">
	<div class="p-1 p-md-5">


		<div id="content">
			<div class="framework-container">
				<div class="example" onpagenavigation id="demo"></div>
			</div>
		</div>
		<div class="clearfix"></div>





	</div>



	<div class="exchange-now">
		<div class="container ">
			<div class="row" style="margin:0px">
				<div class="col-md-5 sync">
					<h2>Exchange</h2>

					<a class="btn btn-default btn-select">
						<input type="hidden" class="btn-select-input" name="" value="" />
						<span class="btn-select-value" value="0">BTC</span>
						<span class='btn-select-arrow fa fa-caret-down'></span>
						<ul id="convert_from">
							<li value="0" class="selected">
								<img src="/static/images/coins/bitcoin.png" width="40px" />BitCoin</li>
							<li value="1">
								<img src="/static/images/coins/eth.png" width="40px" />Ethereum</li>
							<li value="2">
								<img src="/static/images/coins/ltc.png" width="40px" />LiteCoin</li>
							<li value="3">
								<img src="/static/images/coins/xmr.png" width="40px" />Monero</li>
							<li value="4">
								<img src="/static/images/coins/bch.png" width="40px" />BitCoinCash</li>
							<li value="5">
								<img src="/static/images/coins/btg.png" width="40px" />BitCoinGold</li>
						</ul>
					</a>


					<div class="row btn-exchange-input-box-top">
						<div class="col-6">
							<input type="text" value="1" id="convert_amount" class="input-bit" />
						</div>
						<div class="col-6" align="right">
							<span class="from_cur" />
						</div>
					</div>
					<div class="row btn-exchange-input-box-bottom">
						<div class="col-6">
							0.075
						</div>
						<div class="col-6" align="right">
							USD
						</div>
					</div>
				</div>
				<div class="col-md-2 text-center d-flex align-items-center justify-content-center p-5">
					<img src="/static/img/sync.png">
				</div>

				<div class="col-md-5 ">
					<h2>Receive</h2>

					<a class="btn btn-default btn-select">
						<input type="hidden" class="btn-select-input" id="" name="" value="" />
						<span class="btn-select-value" value="2">Litecoin</span>
						<span class='btn-select-arrow fa fa-caret-down'></span>
						<ul id="convert_to">
							<li value="0">
								<img src="/static/images/coins/bitcoin.png" width="40px" />BitCoin</li>
							<li value="1">
								<img src="/static/images/coins/eth.png" width="40px" />Ethereum</li>
							<li value="2" class="selected">
								<img src="/static/images/coins/ltc.png" width="40px" />LiteCoin</li>
							<li value="3">
								<img src="/static/images/coins/xmr.png" width="40px" />Monero</li>
							<li value="4">
								<img src="/static/images/coins/bch.png" width="40px" />BitCoinCash</li>
							<li value="5">
								<img src="/static/images/coins/btg.png" width="40px" />BitCoinGold</li>
						</ul>
					</a>
					<div class="row btn-exchange-input-box-top">
						<div class="col-sm-6">
							<input type="text" disabled id="converted_amount" class="input-bit" />
						</div>
						<div class="col-sm-6" align="right">
							<span class="to_cur" />
						</div>
					</div>
					<div class="row btn-exchange-input-box-bottom">
						<div class="col-6">
							0.075
						</div>
						<div class="col-6" align="right">
							USD
						</div>
					</div>
				</div>



				<div class="col-md-5 ">
					<div class="bit-exchange-value-left">
						<div class="row">

							<div class="col-9 float-right">
								<h4>You are exchanging</h4>
								<p>
									<span class="from_cur" />
								</p>
								<p>4.75 USD</p>
							</div>

							<div class="col-3 d-flex align-items-center ">
								<img id="from_cur_img" src="/static/img/coins/BitCoin.png" class="img-fluid">
							</div>

						</div>
					</div>
				</div>
				<div class="col-md-2 text-center d-flex align-items-center justify-content-center p-5">
					<img src="/static/img/right-arrow.png">
				</div>



				<div class="col-md-5 ">
					<div class="bit-exchange-value-right">
						<div class="row">

							<div class="col-3 d-flex align-items-center ">
								<img id="from_cur_img" src="/static/img/coins/LiteCoin.png" class="img-fluid">
							</div>
							<div class="col-9 float-left">
								<h4>You are receiving</h4>
								<p>
									<span class="from_cur" />
								</p>
								<p>4.75 USD</p>
							</div>


						</div>
					</div>
				</div>
			</div>
			<div align="center">
				<button class="btn btn-exchange mb-3" type="submit" onclick="window.location=''">Exchange now</button>
			</div>
		</div>
	</div>
</section>


{% endblock %} {% block script %}
<script src="{% static 'js/piechart.js' %}"></script>
<script type="text/javascript">
	convertWidget1($('#convert_to').find("li.selected").val());
	$('#convert_from li').click(function (e) {
		convertWidget2(e.target.value);

	})
	$('#convert_to li').click(function (e) {
		convertWidget1(e.target.value);
	})

	$('#convert_amount').keyup(function () {
		convertWidget1($('#convert_to').find("li.selected").val());


	})

	function convertWidget1(convert_to) {
		convert_from = $('#convert_from').find("li.selected").val()
		amount = $('#convert_amount').val()
		$.ajax({
			type: "POST",
			url: "",
			data: {
				'from': convert_from,
				'to': convert_to,
				'amount': amount,
				csrfmiddlewaretoken: '{{ csrf_token }}'
			},
			success: function (data) {
				$("#converted_amount").attr({
					'value': data.result
				});
				from_text = $('#convert_from').find("li.selected").text()
				to_text = $('#convert_to').find("li.selected").text()
				$(".from_cur").text(from_text)
				$(".to_cur").text(to_text)
				$("#from_cur_img").attr({
					"src": "/static/img/coins/" + from_text + ".png"
				})
				$("#to_cur_img").attr({
					"src": "/static/img/coins/" + to_text + ".png"
				})

			}
		})
	}

	function convertWidget2(convert_from) {
		convert_to = $('#convert_to').find("li.selected").val()
		amount = $('#convert_amount').val()
		$.ajax({
			type: "POST",
			url: "",
			data: {
				'from': convert_from,
				'to': convert_to,
				'amount': amount,
				csrfmiddlewaretoken: '{{ csrf_token }}'
			},
			success: function (data) {
				$("#converted_amount").attr({
					'value': data.result
				});
				from_text = $('#convert_from').find("li.selected").text()
				to_text = $('#convert_to').find("li.selected").text()
				$(".from_cur").text(from_text)
				$(".to_cur").text(to_text)
				$("#from_cur_img").attr({
					"src": "/static/img/coins/" + from_text + ".png"
				})
				$("#to_cur_img").attr({
					"src": "/static/img/coins/" + to_text + ".png"
				})

			}
		})
	}
</script>
<script>
	$(".example").piechart([
		["Country", "M inhabitants"],
		["China", 1360, 'blue'],
		["India", 1234],
		["USA", 316],
		["Indonesia", 237],
		["Brazil", 100],
		["keniya", 100],
	]);
	$(".sector-s").trigger("click")
</script>

<script>
	$('.owl-carousel').owlCarousel({
		loop: true,
		margin: 10,
		responsiveClass: true,
		responsive: {
			0: {
				items: 1,
				nav: true
			},
			600: {
				items: 3,
				nav: false
			},
			1000: {
				items: 8,
				nav: true,
				loop: false
			}
		}
	})
</script>

{% endblock %}

templates/pay_in.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section class="col-12">

			<div class="col-sm-6 offset-sm-3 text-center ">
				<img src="https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl={{address}}"></img>
				<h3> Please pay to the following address from your wallet</h3>
				<h4>{{ address }}</h4>
            </div>

</section>
{% endblock %}

templates/welcome.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="font-darkgrey col-12">
<div class="col-sm-12 text-center">
	<h2>Welcome <span class="page-header-font-yellow">{{request.user.first_name}}</span> </h2>
</div>

<section class="col-12">

			<h3 class="">Name: {{request.user.first_name}} {{request.user.last_name}}</h3>
			<h3 class="">Email: {{request.user.email}}</h3>
			<a href="{% url 'auth:logout' %}"> Logout </a>

</section>

<section class="col-12 text-center">
	<!-- market_cap -->
				<h3>CryptoCurrency Market Capitalizations</h3>

				<!-- hanya muncul ketika md dan lg -->
				<div class="d-none d-md-block col-md-10 offset-md-1">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Name</th>
								<th>
									<div class="pull-right">
										Market Cap
									</div>
								</th>
								<th>
									<div class="pull-right">
										Price
									</div>
								</th>
								<th>
									<div class="pull-right">
										Circulating Supply
									</div>
								</th>
								<th>
									<div class="pull-right">
										Volume (24h)
									</div>
								</th>
							</tr>
						</thead>

						<tbody id="marketcap_tbody">

						</tbody>

					</table>
				</div>

				<!-- hanya muncul ketika sm dan xs -->
				<div class="d-md-none d-lg-none d-xl-none bg-dark">
					<div id="marketcap_tbody_small" class="p-5">

					</div>
				</div>

	<!-- end market_cap -->



</section>
</div>
{% endblock %} {% block script %}
<script type="text/javascript">
    Number.prototype.numberFormat = function(decimals, dec_point, thousands_sep) {
        dec_point = typeof dec_point !== 'undefined' ? dec_point : '.';
        thousands_sep = typeof thousands_sep !== 'undefined' ? thousands_sep : ',';

        var parts = this.toFixed(decimals).split('.');
        parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, thousands_sep);

        return parts.join(dec_point);
    }
    </script>
<script type="text/javascript">
	// get list dari coinmarketcap
	function getMarketCap() {

		$.ajax({
			url: 'https://api.coinmarketcap.com/v1/ticker/?limit=10',
			success: function (response) {

				$('tbody#marketcap_tbody').html('');

				$.each(response, function (a, b) {

					$('tbody#marketcap_tbody').append(
						'<tr>' +
						'    <td>' +
						'        ' + b.rank +
						'    </td>' +
						'    <td>' +
						'        ' + b.name +
						'    </td>' +
						'    <td align="right">' +
						'        $ ' + parseFloat(b.market_cap_usd).numberFormat(1, ".", ",") +
						'    </td>' +
						'    <td align="right">' +
						'        $ ' + parseFloat(b.price_usd).numberFormat(5, ".", ",") +
						'    </td>' +
						'    <td align="right">' +
						'        ' + parseFloat(b.available_supply).numberFormat(1, ".", ",") + ' ' + b.symbol +
						'    </td>' +
						'    <td align="right">' +
						'        $ ' + parseFloat(b['24h_volume_usd']).numberFormat(1, ".", ",") +
						'    </td>' +
						'</tr>'
					);

					$('div#marketcap_tbody_small').append(
						'<div style="border-top: 1px solid #fff; padding: 10px auto; margin: 10px auto;">' +
						'    <div class="pt5"><label>Rank</label>:<div>' + b.rank + '</div></div>' +
						'    <div class="pt5"><label>Name</label>:<div>' + b.name + '</div></div>' +
						'    <div class="pt5"><label>Market Cap</label>:<div>' + '$ ' + parseFloat(b.market_cap_usd).numberFormat(1,
							".", ",") + '</div></div>' +
						'    <div class="pt5"><label>Price</label>:<div>$' + parseFloat(b.price_usd).numberFormat(5, ".", ",") +
						'</div></div>' +
						'    <div class="pt5"><label>Circulating Supply</label>:<div>' + parseFloat(b.available_supply).numberFormat(
							1, ".", ",") + ' ' + b.symbol + '</div></div>' +
						'    <div class="pt5"><label>Volume (24h)</label>:<div>$' + parseFloat(b['24h_volume_usd']).numberFormat(1,
							".", ",") + '</div></div>' +
						'</div>'
					);
				});
			}
		});
	}

	(function(){
        // atur menu
        $('.n-menu_dashboard').addClass('active');
        /* ambil data dari coinmarketcap */
        getMarketCap();

        // eksekusi semua crypto balance by interval dan juga data dari coinmarketcap
        setInterval(function(){
            getBtcBalance();
            
            
            

            getMarketCap();
        }, 120000);

    })()
</script>

{% endblock %}